server:
  port: 8095


spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: Guest-Microservice
          uri : lb://Guest-Microservice
          predicates:
            - Path=/guest/**

        - id: Inventory-Microservice
          uri: lb://Inventory-Microservice
          predicates:
              - Path=/inventory/**

        - id: Room-Microservice
          uri: lb://Room-Microservice
          predicates:
              - Path=/room/**

        - id: Reservation-Microservice
          uri: lb://Reservation-Microservice
          predicates:
              - Path=/reservation/**

        - id: Staff-Microservice
          uri: lb://Staff-Microservice
          predicates:
            - Path=/staff/**

        - id: user-service
          uri: lb://Staff-Microservice
          predicates:
            - Path=/**

eureka:
  instance:
    prefer-ip-address: true